[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "moondream"
version = "2.1.1"
description = "Official Python interface for Moondream Cloud and Photon local inference."
authors = [ "M87 Labs <contact@moondream.ai>",]
readme = "README.md"
include = ["CHANGELOG.md"]
[[tool.poetry.packages]]
include = "moondream"
from = "."

[tool.pyright]
venvPath = "."
venv = ".venv"
reportMissingParameterType = false

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
pillow = ">=10.4.0"
kestrel = "0.7.0"
